testing automation flow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -125,117 +125,117 @@ jobs:
           fi
 
       
-      - name: Build the image and update the container app
-        id: build-and-update
-        run: |
-
-          set -e
-          # Define variables for acr and container app names
-          acr_name="${{ env.ACR_NAME }}"
-          echo "ACR name: {$acr_name}"
-          backend_container_app_name="macae-backend"
-          backend_build_image_tag="backend:latest"
-
-          echo "Building the container image..."
-          # Build the image
-          az acr build -r ${acr_name} -t ${backend_build_image_tag} ./src/backend
-          echo "Backend image build completed successfully."
-
-          frontend_container_app_name="${{ env.APP_SERVICE_NAME }}"
-          frontend_build_image_tag="frontend:latest"
-
-          echo "Building the container image..."
-          # Build the image
-          az acr build -r ${acr_name} -t ${frontend_build_image_tag} ./src/frontend
-          echo "Frontend image build completed successfully."
-
-          # Add the new container to the website
-          az webapp config container set --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${frontend_container_app_name} --container-image-name ${acr_name}.azurecr.io/frontend:latest --container-registry-url https://${acr_name}.azurecr.io
-                  
-          
-      - name: Delete Bicep Deployment
-        if: success()
-        run: |
-          set -e  
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-          if [ "$rg_exists" = "true" ]; then
-            echo "Resource group exist. Cleaning..."
-            az group delete \
-                --name ${{ env.RESOURCE_GROUP_NAME }} \
-                --yes \
-                --no-wait
-            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
-          else
-            echo "Resource group does not exists."
-          fi
-
-
-      - name: Wait for resource deletion to complete
-        run: |
-
-          
-          # Add resources to the array
-          resources_to_check=("${{ env.OPENAI_RESOURCE_NAME }}")
-
-          echo "List of resources to check: ${resources_to_check[@]}"
-
-          # Maximum number of retries
-          max_retries=3
-
-          # Retry intervals in seconds (30, 60, 120)
-          retry_intervals=(30 60 120)
-
-          # Retry mechanism to check resources
-          retries=0
-          while true; do
-            resource_found=false
-
-            # Get the list of resources in YAML format again on each retry
-            resource_list=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --output yaml)
-
-            # Iterate through the resources to check
-            for resource in "${resources_to_check[@]}"; do
-              echo "Checking resource: $resource"
-              if echo "$resource_list" | grep -q "name: $resource"; then
-                echo "Resource '$resource' exists in the resource group."
-                resource_found=true
-              else
-                echo "Resource '$resource' does not exist in the resource group."
-              fi
-            done
-
-            # If any resource exists, retry
-            if [ "$resource_found" = true ]; then
-              retries=$((retries + 1))
-              if [ "$retries" -gt "$max_retries" ]; then
-                echo "Maximum retry attempts reached. Exiting."
-                break
-              else
-                # Wait for the appropriate interval for the current retry
-                echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
-                sleep ${retry_intervals[$retries-1]}
-              fi
-            else
-              echo "No resources found. Exiting."
-              break
-            fi
-          done
-
-          
-      # - name: Purging the Resources
-      #   if: success()
+      # - name: Build the image and update the container app
+      #   id: build-and-update
       #   run: |
 
-      #     set -e 
-      #     echo "Azure OpenAI: ${{ env.OPENAI_RESOURCE_NAME }}"
+      #     set -e
+      #     # Define variables for acr and container app names
+      #     acr_name="${{ env.ACR_NAME }}"
+      #     echo "ACR name: {$acr_name}"
+      #     backend_container_app_name="macae-backend"
+      #     backend_build_image_tag="backend:latest"
 
-      #     # Purge OpenAI Resource
-      #     echo "Purging the OpenAI Resource..."
-      #     if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/${{ env.OPENAI_RESOURCE_NAME }} --verbose; then
-      #       echo "Failed to purge openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+      #     echo "Building the container image..."
+      #     # Build the image
+      #     az acr build -r ${acr_name} -t ${backend_build_image_tag} ./src/backend
+      #     echo "Backend image build completed successfully."
+
+      #     frontend_container_app_name="${{ env.APP_SERVICE_NAME }}"
+      #     frontend_build_image_tag="frontend:latest"
+
+      #     echo "Building the container image..."
+      #     # Build the image
+      #     az acr build -r ${acr_name} -t ${frontend_build_image_tag} ./src/frontend
+      #     echo "Frontend image build completed successfully."
+
+      #     # Add the new container to the website
+      #     az webapp config container set --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${frontend_container_app_name} --container-image-name ${acr_name}.azurecr.io/frontend:latest --container-registry-url https://${acr_name}.azurecr.io
+                  
+          
+      # - name: Delete Bicep Deployment
+      #   if: success()
+      #   run: |
+      #     set -e  
+      #     echo "Checking if resource group exists..."
+      #     rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+      #     if [ "$rg_exists" = "true" ]; then
+      #       echo "Resource group exist. Cleaning..."
+      #       az group delete \
+      #           --name ${{ env.RESOURCE_GROUP_NAME }} \
+      #           --yes \
+      #           --no-wait
+      #       echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
       #     else
-      #       echo "Purged the openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+      #       echo "Resource group does not exists."
       #     fi
 
-      #     echo "Resource purging completed successfully"
+
+      # - name: Wait for resource deletion to complete
+      #   run: |
+
+          
+      #     # Add resources to the array
+      #     resources_to_check=("${{ env.OPENAI_RESOURCE_NAME }}")
+
+      #     echo "List of resources to check: ${resources_to_check[@]}"
+
+      #     # Maximum number of retries
+      #     max_retries=3
+
+      #     # Retry intervals in seconds (30, 60, 120)
+      #     retry_intervals=(30 60 120)
+
+      #     # Retry mechanism to check resources
+      #     retries=0
+      #     while true; do
+      #       resource_found=false
+
+      #       # Get the list of resources in YAML format again on each retry
+      #       resource_list=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --output yaml)
+
+      #       # Iterate through the resources to check
+      #       for resource in "${resources_to_check[@]}"; do
+      #         echo "Checking resource: $resource"
+      #         if echo "$resource_list" | grep -q "name: $resource"; then
+      #           echo "Resource '$resource' exists in the resource group."
+      #           resource_found=true
+      #         else
+      #           echo "Resource '$resource' does not exist in the resource group."
+      #         fi
+      #       done
+
+      #       # If any resource exists, retry
+      #       if [ "$resource_found" = true ]; then
+      #         retries=$((retries + 1))
+      #         if [ "$retries" -gt "$max_retries" ]; then
+      #           echo "Maximum retry attempts reached. Exiting."
+      #           break
+      #         else
+      #           # Wait for the appropriate interval for the current retry
+      #           echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
+      #           sleep ${retry_intervals[$retries-1]}
+      #         fi
+      #       else
+      #         echo "No resources found. Exiting."
+      #         break
+      #       fi
+      #     done
+
+          
+      - name: Purging the Resources
+        if: success()
+        run: |
+
+          set -e 
+          echo "Azure OpenAI: ${{ env.OPENAI_RESOURCE_NAME }}"
+
+          # Purge OpenAI Resource
+          echo "Purging the OpenAI Resource..."
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/${{ env.OPENAI_RESOURCE_NAME }} --verbose; then
+            echo "Failed to purge openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+          else
+            echo "Purged the openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+          fi
+
+          echo "Resource purging completed successfully"
