testing automation flow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,7 +30,8 @@ jobs:
           echo "Generating a unique resource group name..."
           TIMESTAMP=$(date +%Y%m%d%H%M%S)
           COMMON_PART="ci-biab"
-          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          # UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          UNIQUE_RG_NAME="rg-biab-hotfix"
           echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
           echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
       
@@ -49,33 +50,33 @@ jobs:
           fi
 
 
-      - name: Deploy Bicep Template
-        id: deploy
-        run: |
-          set -e
-          az deployment group create \
-            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
-            --template-file deploy/macae.bicep \
-            --parameters azureOpenAILocation=eastus2 cosmosLocation=eastus2
+      # - name: Deploy Bicep Template
+      #   id: deploy
+      #   run: |
+      #     set -e
+      #     az deployment group create \
+      #       --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
+      #       --template-file deploy/macae.bicep \
+      #       --parameters azureOpenAILocation=eastus2 cosmosLocation=eastus2
 
 
-      - name: Send Notification on Failure
-        if: failure()
-        run: |
-          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      # - name: Send Notification on Failure
+      #   if: failure()
+      #   run: |
+      #     RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
       
-          # Construct the email body
-          EMAIL_BODY=$(cat <<EOF
-          {
-            "body": "<p>Dear Team,</p><p>We would like to inform you that the Multi-Agent-Custom-Automation-Engine-Solution-Accelerator Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
-          }
-          EOF
-          )
+      #     # Construct the email body
+      #     EMAIL_BODY=$(cat <<EOF
+      #     {
+      #       "body": "<p>Dear Team,</p><p>We would like to inform you that the Multi-Agent-Custom-Automation-Engine-Solution-Accelerator Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
+      #     }
+      #     EOF
+      #     )
       
-          # Send the notification
-          curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
-            -H "Content-Type: application/json" \
-            -d "$EMAIL_BODY" || echo "Failed to send notification"
+      #     # Send the notification
+      #     curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
+      #       -H "Content-Type: application/json" \
+      #       -d "$EMAIL_BODY" || echo "Failed to send notification"
   
     
       - name: Get OpenAI, Container Registry Resource from Resource Group
@@ -110,112 +111,138 @@ jobs:
             echo "Azure Container Registry name: ${acr_name}"
           fi
 
-      
-      - name: Build the image and update the container app
-        id: build-and-update
+      - name: Get Azure App Service Resource from Resource Group
+        id: get_app_service_resource
         run: |
-
           set -e
-          # Define variables for acr and container app names
-          acr_name="${{ env.ACR_NAME }}"
-          echo "ACR name: {$acr_name}"
-          container_app_name="biab"
-          buildImageTag="biab:latest"
+          echo "Fetching Azure App Service resource from resource group ${{ env.RESOURCE_GROUP_NAME }}..."
+          
+          # Run the az resource list command to get the App Service resource name
+          app_service_name=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --resource-type "Microsoft.Web/sites" --query "[0].name" -o tsv)
 
-          echo "Building the container image..."
-          # Build the image
-          az acr build -r ${acr_name} -t ${buildImageTag} ./agnext-biab-02
-          echo "Image build completed successfully."
+          if [ -z "$app_service_name" ]; then
+            echo "No Azure App Service resource found in resource group ${{ env.RESOURCE_GROUP_NAME }}."
+            exit 1
+          else
+            echo "APP_SERVICE_NAME=${app_service_name}" >> $GITHUB_ENV
+            echo "Azure App Service resource name: ${app_service_name}" 
+          fi
 
-          echo "Updating the container app..."
-          # Update the container app
-          az containerapp update -n ${container_app_name} -g ${{ env.RESOURCE_GROUP_NAME }} --image ${acr_name}.azurecr.io/${buildImageTag}
-          echo "Container app update completed successfully."
+
+      
+      # - name: Build the image and update the container app
+      #   id: build-and-update
+      #   run: |
+
+      #     set -e
+      #     # Define variables for acr and container app names
+      #     acr_name="${{ env.ACR_NAME }}"
+      #     echo "ACR name: {$acr_name}"
+      #     backend_container_app_name="macae-backend"
+      #     buildImageTag="backend:latest"
+
+      #     echo "Building the container image..."
+      #     # Build the image
+      #     az acr build -r ${acr_name} -t ${buildImageTag} ./agnext-biab-02
+      #     echo "Backend image build completed successfully."
+
+      #     echo "Updating the container app..."
+      #     # Update the container app
+      #     az containerapp update -n ${container_app_name} -g ${{ env.RESOURCE_GROUP_NAME }} --image ${acr_name}.azurecr.io/${buildImageTag}
+      #     echo "Backend container app update completed successfully."
+
+      #     frontend_container_app_name="macae-backend"
+      #     buildImageTag="backend:latest"
+
+      #     echo "Building the container image..."
+      #     # Build the image
+      #     az acr build -r ${acr_name} -t ${buildImageTag} ./agnext-biab-02
+      #     echo "Image build completed successfully."
         
           
-      - name: Delete Bicep Deployment
-        if: success()
-        run: |
-          set -e  
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-          if [ "$rg_exists" = "true" ]; then
-            echo "Resource group exist. Cleaning..."
-            az group delete \
-                --name ${{ env.RESOURCE_GROUP_NAME }} \
-                --yes \
-                --no-wait
-            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
-          else
-            echo "Resource group does not exists."
-          fi
+      # - name: Delete Bicep Deployment
+      #   if: success()
+      #   run: |
+      #     set -e  
+      #     echo "Checking if resource group exists..."
+      #     rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+      #     if [ "$rg_exists" = "true" ]; then
+      #       echo "Resource group exist. Cleaning..."
+      #       az group delete \
+      #           --name ${{ env.RESOURCE_GROUP_NAME }} \
+      #           --yes \
+      #           --no-wait
+      #       echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
+      #     else
+      #       echo "Resource group does not exists."
+      #     fi
 
 
-      - name: Wait for resource deletion to complete
-        run: |
-
-          
-          # Add resources to the array
-          resources_to_check=("${{ env.OPENAI_RESOURCE_NAME }}")
-
-          echo "List of resources to check: ${resources_to_check[@]}"
-
-          # Maximum number of retries
-          max_retries=3
-
-          # Retry intervals in seconds (30, 60, 120)
-          retry_intervals=(30 60 120)
-
-          # Retry mechanism to check resources
-          retries=0
-          while true; do
-            resource_found=false
-
-            # Get the list of resources in YAML format again on each retry
-            resource_list=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --output yaml)
-
-            # Iterate through the resources to check
-            for resource in "${resources_to_check[@]}"; do
-              echo "Checking resource: $resource"
-              if echo "$resource_list" | grep -q "name: $resource"; then
-                echo "Resource '$resource' exists in the resource group."
-                resource_found=true
-              else
-                echo "Resource '$resource' does not exist in the resource group."
-              fi
-            done
-
-            # If any resource exists, retry
-            if [ "$resource_found" = true ]; then
-              retries=$((retries + 1))
-              if [ "$retries" -gt "$max_retries" ]; then
-                echo "Maximum retry attempts reached. Exiting."
-                break
-              else
-                # Wait for the appropriate interval for the current retry
-                echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
-                sleep ${retry_intervals[$retries-1]}
-              fi
-            else
-              echo "No resources found. Exiting."
-              break
-            fi
-          done
+      # - name: Wait for resource deletion to complete
+      #   run: |
 
           
-      - name: Purging the Resources
-        if: success()
-        run: |
+      #     # Add resources to the array
+      #     resources_to_check=("${{ env.OPENAI_RESOURCE_NAME }}")
 
-          set -e 
-          echo "Azure OpenAI: ${{ env.OPENAI_RESOURCE_NAME }}"
+      #     echo "List of resources to check: ${resources_to_check[@]}"
 
-          # Purge OpenAI Resource
-          echo "Purging the OpenAI Resource..."
-          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/${{ env.OPENAI_RESOURCE_NAME }} --verbose; then
-            echo "Failed to purge openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
-          else
-            echo "Purged the openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
-          fi
+      #     # Maximum number of retries
+      #     max_retries=3
 
-          echo "Resource purging completed successfully"
+      #     # Retry intervals in seconds (30, 60, 120)
+      #     retry_intervals=(30 60 120)
+
+      #     # Retry mechanism to check resources
+      #     retries=0
+      #     while true; do
+      #       resource_found=false
+
+      #       # Get the list of resources in YAML format again on each retry
+      #       resource_list=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --output yaml)
+
+      #       # Iterate through the resources to check
+      #       for resource in "${resources_to_check[@]}"; do
+      #         echo "Checking resource: $resource"
+      #         if echo "$resource_list" | grep -q "name: $resource"; then
+      #           echo "Resource '$resource' exists in the resource group."
+      #           resource_found=true
+      #         else
+      #           echo "Resource '$resource' does not exist in the resource group."
+      #         fi
+      #       done
+
+      #       # If any resource exists, retry
+      #       if [ "$resource_found" = true ]; then
+      #         retries=$((retries + 1))
+      #         if [ "$retries" -gt "$max_retries" ]; then
+      #           echo "Maximum retry attempts reached. Exiting."
+      #           break
+      #         else
+      #           # Wait for the appropriate interval for the current retry
+      #           echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
+      #           sleep ${retry_intervals[$retries-1]}
+      #         fi
+      #       else
+      #         echo "No resources found. Exiting."
+      #         break
+      #       fi
+      #     done
+
+          
+      # - name: Purging the Resources
+      #   if: success()
+      #   run: |
+
+      #     set -e 
+      #     echo "Azure OpenAI: ${{ env.OPENAI_RESOURCE_NAME }}"
+
+      #     # Purge OpenAI Resource
+      #     echo "Purging the OpenAI Resource..."
+      #     if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/${{ env.OPENAI_RESOURCE_NAME }} --verbose; then
+      #       echo "Failed to purge openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+      #     else
+      #       echo "Purged the openai resource: ${{ env.OPENAI_RESOURCE_NAME }}"
+      #     fi
+
+      #     echo "Resource purging completed successfully"
